---
title: Story time
hero_image: images/banner.png
description: Generate fairy tales and other imaginative stories with basic Python
original_url: https://raspberrypi.org/learning/storytime
theme: yellow
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Input and output
- title: If or else
- title: Lists
- title: Using Random
- title: Story Time!
- title: "Challenge: more lists"
  challenge: true
- title: What next?
