---
title: Storytime
hero_image: images/banner.png
description: Generate fairy tales and other imaginative stories with basic Python
original_url: https://raspberrypi.org/learning/storytime
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Using IDLE on Raspberry Pi
- title: Using Trinket
- title: Get User Input and Print to the Screen
- title: If, Elif, and Else
- title: Lists
- title: Using Random
- title: Story Time!
- title: The Final Print
- title: What next?

