---
title: Story time
hero_image: images/banner.png
description: Create interactive fairy tales and other stories with basic Python
original_url: https://raspberrypi.org/learning/storytime
theme: yellow
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: रास्पबेरी-पीआई, इलेक्ट्रॉनिक-घटक, Python
site_areas: प्रोजेक्ट
hardware: रास्पबेरी-पीआई, इलेक्ट्रॉनिक-घटक
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: Make your story interactive
  - 
    title: Big or small, old or young
  - 
    title: Lists of details
  - 
    title: Choose your story details
  - 
    title: Tell your story
  - 
    title: "Challenge: add more details"
    challenge: true
  - 
    title: What next?
