---
title: Storytime
hero_image: images/banner.png
description: Generate fairy tales and other imaginative stories with basic Python
original_url: https://raspberrypi.org/learning/storytime
theme: yellow
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, disseny-0, programació-2, phys-comp-0, fabricació-0, comunitat-0
interests: ''
technologies: raspberry-pi, electronic-components, python
site_areas: projectes
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Using IDLE on Raspberry Pi
  - 
    title: Using Trinket
  - 
    title: Get User Input and Print to the Screen
  - 
    title: If, Elif, and Else
  - 
    title: Lists
  - 
    title: Using Random
  - 
    title: Story Time!
  - 
    title: The Final Print
  - 
    title: I ara què ve?
