---
title: Storytime
hero_image: images / banner.png
description: Generate fairy tales and other imaginative stories with basic Python
original_url: https://raspberrypi.org/learning/storytime
theme: 노란
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, 디자인 -0, 프로그래밍 -2, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: ''
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: Using IDLE on Raspberry Pi
  - 
    title: Using Trinket
  - 
    title: Get User Input and Print to the Screen
  - 
    title: If, Elif, and Else
  - 
    title: Python 리스트
  - 
    title: Using Random
  - 
    title: Story Time!
  - 
    title: The Final Print
  - 
    title: '도전과제: 더 많은 연필들'
