---
title: Storytime
hero_image: images/banner.png
description: Generate fairy tales and other imaginative stories with basic Python
original_url: https://raspberrypi.org/learning/storytime
theme: gul
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programmering-2, phys-comp-0, tillverkning-0, community-0
interests: ''
technologies: raspberry-pi, electronic-components, python
site_areas: projekt
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduktion
  - 
    title: Vad du kommer att behöva
  - 
    title: Using IDLE on Raspberry Pi
  - 
    title: Using Trinket
  - 
    title: Get User Input and Print to the Screen
  - 
    title: If, Elif, and Else
  - 
    title: Lists
  - 
    title: Using Random
  - 
    title: Story Time!
  - 
    title: The Final Print
  - 
    title: What next?
