---
title: L'heure des histoires
hero_image: images/banner.png
description: Créer des contes de fées interactifs et d'autres histoires avec les bases de Python
original_url: https://raspberrypi.org/learning/storytime
theme: yellow
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
    completion: engaged
  - 
    title: Rendre ton histoire interactive
  - 
    title: Grand ou petit, ancien ou jeune
  - 
    title: Listes de détails
  - 
    title: Choisir les détails de ton histoire
    completion: internal
  - 
    title: Raconter ton histoire
  - 
    title: 'Défi : ajoute plus de détails'
    challenge: true
  - 
    title: Et ensuite ?
